/**
 * Swagger todo-api
 * Api definition for todos.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("TodoApi", () => {
  let instance: api.TodoApi
  beforeEach(function() {
    instance = new api.TodoApi(config)
  });

  test("addTodo", () => {
    const body: api.PostTodo = {
      name: ""
    }
    const authToken: string = "authToken_example"
    return expect(instance.addTodo(body, authToken, {})).resolves.toBe(null)
  })
  test("deleteTodo", () => {
    const authToken: string = "authToken_example"
    const todoId: string = "todoId_example"
    return expect(instance.deleteTodo(authToken, todoId, {})).resolves.toBe(null)
  })
  test("getTodoHistory", () => {
    const authToken: string = "authToken_example"
    const todoId: string = "todoId_example"
    return expect(instance.getTodoHistory(authToken, todoId, {})).resolves.toBe(null)
  })
  test("getTodos", () => {
    const authToken: string = "authToken_example"
    return expect(instance.getTodos(authToken, {})).resolves.toBe(null)
  })
  test("updateTodo", () => {
    const authToken: string = "authToken_example"
    const todoId: string = "todoId_example"
    const body: api.UpdateTodo = {
      name:"",
      status: ""
    }
    return expect(instance.updateTodo(authToken, todoId, body, {})).resolves.toBe(null)
  })
})

