openapi: 3.0.3
info:
  title: Swagger todo-api
  description: |-
    Api definition for todos.
  version: 1.0.0
tags:
  - name: todo
    description: todo of an organization
paths:
  /todos:
    get:
      tags:
        - todo
      summary: fetch all todos
      description: fetch todos
      operationId: getTodos
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/allTodos'
        '404':
          description: No todos found
        '405':
          description: Validation exception
    post:
      tags:
        - todo
      summary: Add a new todo
      description: Add a new todo of an org
      operationId: addTodo
      parameters:
        - name: auth-token
          in: header
          description: login-token to authorize user
          required: true
          schema:
            type: string
      requestBody:
        description: Create a new todo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postTodo'
        required: true
      responses:
        '201':
          description: Successful todo creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseTodo'          
        '405':
          description: Invalid input
  /todos/{todoId}:
    put:
      tags:
        - todo
      summary: Update todo by ID
      description: Update todo by Id
      operationId: updateTodo
      parameters:
        - name: auth-token
          in: header
          description: login-token to authorize user
          required: true
          schema:
            type: string
        - name: todoId
          in: path
          description: ID of todo to update
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successfully updated todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseTodo'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Todo not found
    delete:
      tags:
        - todo
      summary: Deletes a todo
      description: delete a todo
      operationId: deleteTodo
      parameters:
        - name: auth-token
          in: header
          description: login-token to authorize user
          required: true
          schema:
            type: string
        - name: todoId
          in: path
          description: todo id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successfully deleted todo
        '400':
          description: Invalid todo id
  
components:
  schemas:
    postTodo:
      required:
        - id
        - name
        - status
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example: ReadBook
        status:
          type: string
          description: todo status for an org
          enum:
            - pending
            - processing
            - done
            - cancelled
    allTodos:
      type: array
      items:
        properties:
          id:
            type: string
          name:
            type: string
            example: ReadBook
          status:
            type: string
            description: todo status for an org
            enum:
              - pending
              - processing
              - done
              - cancelled
    responseTodo:
      required:
        - id
        - name
        - status
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example: ReadBook
        status:
          type: string
          description: todo status for an org
          enum:
            - pending
            - processing
            - done
            - cancelled
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/KHANMAZHAR72/todo/1.0.0
x-aws-api-id: '3194x03fwa'