/**
 *  This code was generated by SwaggerHub from the following API:
 * 
 *  https://app.swaggerhub.com/api/KHANMAZHAR72/todo/1.0.0
 *  
 *  The content of this file will never be modified after initial
 *  generation--adding or changing parameters will not be reflected
 *  here.  You can regenerate this with the latest definition by
 *  deleting the lambda and allowing SwaggerHub to recreate it
 **/

const { DynamoDBClient,PutItemCommand,GetItemCommand } = require('@aws-sdk/client-dynamodb');
const { v4: uuidv4 } = require('uuid');
const REGION = `us-east-1`; // Put your correct aws region
const ddbClient = new DynamoDBClient({ region: REGION });
exports.handler = async function(event, context, callback) {
  // header: (required)  login-token to authorize user
  // var auth-token = event.auth-token;
  // path: (required)  ID of todo to update
  
  const body = event.body
  const authToken = event.authToken; 
  const parsedtodoId = event.todoId;
  const todoId = parsedtodoId;
  const currDateTime = new Date();
  // const DateTimeFormat = currDateTime.toISOString();
  const stateId = uuidv4();
  let isStateSet = false
  const actionPerformerOrgId = 'OrgID#98765'
  const actionPerformerUserId = 'UserID#12345'
  let newTodo = {};
  let response={
    message: '',
    errType: '',
    statusCode: null,
    updatedTodo: {}
  };
  let targetTodo = {};
  
  if(!authToken || authToken === ""){
    response.message = 'Not a Authenticated user.';
    response.statusCode = 401;
    return response;
  }
  if((body.name === undefined || body.name === "") && (body.status === undefined || body.status === "")){
    response.message = 'Invalid input provided.';
    response.statusCode = 400
    return response;
  }
  if(!todoId){
    response.message = 'Invalid input provided.';
    response.statusCode = 400;
    return response;
  }
  console.log("lambda evnt-body vars, ", body, parsedtodoId);
   
  const name =body["name"];
  const status = body["status"];
  

  //for update, first update the master record i.e todoId#:todoId# status to current state and than create a record for history
  const getTodoParams = {
    TableName: "TodosList",
    Item: {
      PK: {S: `${actionPerformerOrgId}:${actionPerformerUserId}`},
      SK: {S: `TodoId#${todoId}:TodoId#${todoId}`},  //TodoId#${todoId}:TodoId#${todoId}
      Name: {S: `${name}`},
      State: {S:`${status}`},
      time: {S:`${currDateTime}`}
    }
  };
  const getTodo = {
    TableName: "TodosList",
    Key: {
      PK: {S: `${actionPerformerOrgId}:${actionPerformerUserId}`},
      SK: {S:`TodoId#${todoId}:TodoId#${todoId}`}
    }
  };
  
  try {
    const data = await ddbClient.send(new GetItemCommand(getTodo));
    console.log(data, "record to be updated...");
    if(data.$metadata && data.$metadata.httpStatusCode === 200){
      isStateSet = true
      targetTodo = data.Item;

      if(isStateSet){
        
        const todoState = (status && status !== "") ? status : targetTodo.State.S;
        const todoName = (name === "" || !name) ? targetTodo.Name.S : name;
        getTodoParams.Item.State.S = todoState;
        getTodoParams.Item.Name.S = todoName;
        const prevSK = targetTodo.SK.S;
        // getTodoParams.Item.SK.S = `${prevSK}:State#${todoState}`; //update history(child record)
        try {
          const data = await ddbClient.send(new PutItemCommand(getTodoParams));
          console.log("updation result,", data)
          if(data && data.$metadata && data.$metadata.httpStatusCode === 200){
            response.message = 'Successfully updated  master record';
            response.statusCode = 200;
          }
        } catch (err) {
          response.message = err.errorMessage;
          response.errType = err.errorType;
          response.statusCode = 500;
          return response;
        }
        const childParam = prevSK.substr(0,33);
        getTodoParams.Item.SK.S = `${childParam}:State#${todoState}`;
        console.log(getTodoParams, "params to be updated...")
        try {
          const data = await ddbClient.send(new PutItemCommand(getTodoParams));
          console.log("updation result,", data)
          if(data && data.$metadata && data.$metadata.httpStatusCode === 200){
            response.message = 'Successfully updated child record';
            response.statusCode = 200;
          }
        } catch (err) {
          response.message = err.errorMessage;
          response.errType = err.errorType;
          response.statusCode = 500;
          return response;
        }
      }
    }
    } catch (err) {
      response.message = err.errorMessage;
      response.errType = err.errorType;
      response.statusCode = 500;
      return response;
    }

    try {
        console.log("updation done, now fetching updated todo...")
        const todoState = (status && status !== "") ? status : targetTodo.State.S;
        
        newTodo = await ddbClient.send(new GetItemCommand({
        TableName: "TodosList",
        Key: {
            PK: {S: `${actionPerformerOrgId}:${actionPerformerUserId}`},
            SK: {S:`TodoId#${todoId}:TodoId#${todoId}`},
            }
        }));
        console.log("updation done, now fetching updated todo...", newTodo)
        console.log(newTodo, "updatedTodo here...");
        
        let keys = Object.keys(newTodo.Item);
        
        for(let i=0;i<keys.length;i++){
          const val = newTodo.Item[keys[i]].S;
          response.updatedTodo[keys[i]] = val;
        }
        } catch (err) {
            console.log("updation done, fetching updated todo failed...", err)
            response.message = err.errorMessage;
            response.errType = err.errorType;
            response.statusCode = 500;
            return response;
        }
        
    if(response.statusCode === 200){
      return response;
    }
    return response;
};