/**
 *  This code was generated by SwaggerHub from the following API:
 * 
 *  https://app.swaggerhub.com/api/KHANMAZHAR72/todo/1.0.0
 *  
 *  The content of this file will never be modified after initial
 *  generation--adding or changing parameters will not be reflected
 *  here.  You can regenerate this with the latest definition by
 *  deleting the lambda and allowing SwaggerHub to recreate it
 **/
const { DynamoDBClient,ScanCommand } = require('@aws-sdk/client-dynamodb');
const REGION = `us-east-1`; // Put your correct aws region
const ddbClient = new DynamoDBClient({ region: REGION });
exports.handler = async function(event, context, callback) {
  let response={
    message: '',
    todos: [],
    statusCode: null
  };
  const params = {
    TableName: 'todoOrg'
   };
  try {
    let tempTodo =[]
    const data = await ddbClient.send(new ScanCommand(params));
    console.log(data);
    if(data.$metadata && data.$metadata.httpStatusCode === 200){
      response.todos = data.Items;
      // tempTodo = data.Items;
      response.statusCode = data.$metadata.httpStatusCode;
      // data.Items.map(item=>{
      //   let keys = Object.keys(item);
      //   for(let i=0;i<keys.length;i++){
      //     response.todos[keys[i]] = tempTodo[keys[i]]["S"]
      //   }
      // })
    }
    } catch (err) {
      response = err
      console.error(err);
    }
    return response;
};